import { BattleMapEntity } from '../../types/map';

export const STARTER_MAPS: BattleMapEntity[] = [
  {
    id: 'map-cragmaw-cave',
    type: 'map' as any,
    campaignId: 'campaign-phandalin',
    name: 'Cragmaw Hideout - Chief Lair',
    description: 'A damp cavern complex with stone stalactites, goblin lookouts, and Klarg the Bugbears treasure chamber.',
    imageUrl: '', // Will generate a grid pattern or allow custom image
    width: 1400,
    height: 1000,
    grid: {
      enabled: true,
      type: 'square',
      cellSize: 50,
      offsetX: 0,
      offsetY: 0,
      color: '#ffffff',
      opacity: 0.2,
      feetPerCell: 5,
      snapToGrid: true,
    },
    lighting: {
      ambientLight: 'dark',
      dynamicLosEnabled: true,
      fogOfWarEnabled: true,
      gmVision: false,
    },
    walls: [
      // Outer Room 1 (Main Entrance)
      { id: 'w1', p1: { x: 100, y: 100 }, p2: { x: 500, y: 100 }, type: 'wall' },
      { id: 'w2', p1: { x: 500, y: 100 }, p2: { x: 500, y: 300 }, type: 'wall' },
      { id: 'w3', p1: { x: 500, y: 300 }, p2: { x: 500, y: 400 }, type: 'door', isOpen: false },
      { id: 'w4', p1: { x: 500, y: 400 }, p2: { x: 500, y: 600 }, type: 'wall' },
      { id: 'w5', p1: { x: 500, y: 600 }, p2: { x: 100, y: 600 }, type: 'wall' },
      { id: 'w6', p1: { x: 100, y: 600 }, p2: { x: 100, y: 100 }, type: 'wall' },

      // Inner Room 2 (Klarg's Throne Room)
      { id: 'w7', p1: { x: 500, y: 100 }, p2: { x: 1000, y: 100 }, type: 'wall' },
      { id: 'w8', p1: { x: 1000, y: 100 }, p2: { x: 1000, y: 600 }, type: 'wall' },
      { id: 'w9', p1: { x: 1000, y: 600 }, p2: { x: 500, y: 600 }, type: 'wall' },

      // Secret Escape Tunnel
      { id: 'w11', p1: { x: 1000, y: 350 }, p2: { x: 1000, y: 450 }, type: 'secretDoor', isOpen: false },
      { id: 'w12', p1: { x: 1000, y: 350 }, p2: { x: 1300, y: 350 }, type: 'wall' },
      { id: 'w13', p1: { x: 1000, y: 450 }, p2: { x: 1300, y: 450 }, type: 'wall' },
    ],
    tokens: [
      {
        id: 't-eldrin',
        entityId: 'char-eldrin',
        name: 'Eldrin Valen',
        isPlayer: true,
        x: 225,
        y: 375,
        size: 1,
        elevation: 0,
        currentHp: 28,
        maxHp: 28,
        armorClass: 18,
        senses: {
          normalSight: 60,
          darkvision: 60, // Half-elf darkvision
          blindsight: 0,
          truesight: 0,
          tremorsense: 0,
        },
      },
      {
        id: 't-lyra',
        entityId: 'char-lyra',
        name: 'Lyra Shadowswift',
        isPlayer: true,
        x: 275,
        y: 425,
        size: 1,
        elevation: 0,
        currentHp: 21,
        maxHp: 21,
        armorClass: 15,
        senses: {
          normalSight: 60,
          darkvision: 60,
          blindsight: 0,
          truesight: 0,
          tremorsense: 0,
        },
      },
      {
        id: 't-goblin-1',
        entityId: 'srd-goblin',
        name: 'Goblin Lookout',
        isPlayer: false,
        x: 475,
        y: 225,
        size: 1,
        elevation: 0,
        currentHp: 7,
        maxHp: 7,
        armorClass: 15,
        senses: {
          normalSight: 60,
          darkvision: 60,
          blindsight: 0,
          truesight: 0,
          tremorsense: 0,
        },
      },
      {
        id: 't-klarg',
        entityId: 'srd-bugbear',
        name: 'Klarg the Bugbear',
        isPlayer: false,
        x: 775,
        y: 375,
        size: 1,
        elevation: 0,
        currentHp: 27,
        maxHp: 27,
        armorClass: 16,
        senses: {
          normalSight: 60,
          darkvision: 60,
          blindsight: 0,
          truesight: 0,
          tremorsense: 0,
        },
      },
    ],
    fogOfWar: {
      enabled: false,
      opacity: 0.85,
      revealedAreas: [],
    },
    drawings: [],
    pins: [
      {
        id: 'pin-chimney',
        x: 750,
        y: 180,
        title: "Klarg's Treasure Chest & Chimney",
        description: 'Contains 600 cp, 110 sp, two potions of healing, and an emerald statuette of a frog.',
        icon: 'Sparkles',
      },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];
