import { GenericLootItem } from '../../types/loot';
import { RollTableEntity } from '../../types/rollTable';

export const GENERAL_LOOT_ITEMS: GenericLootItem[] = [
  {
    "name": "Filigreed Silver Censer",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Aged",
    "rarity": "Common",
    "description": "An ornate silver incense burner suspended by three fine chains, etched with prayers to a forgotten deity."
  },
  {
    "name": "Carved Obsidian Prayer Beads",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A strand of 108 polished black obsidian beads with a small silver crescent icon at the tassel."
  },
  {
    "name": "Vellum Holy Manuscript with Gold Leaf",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "150 gp",
    "valueGp": 150,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Fragile",
    "rarity": "Uncommon",
    "description": "An ancient theological tome bound in cracked leather, its illuminated script decorated with real gold leaf."
  },
  {
    "name": "Ivory Icon of an Ancient Deity",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Aged",
    "rarity": "Uncommon",
    "description": "A hand-carved walrus ivory figurine depicting a multi-armed sun god with gemstone-set eyes."
  },
  {
    "name": "Tarnished Bronze Offering Bowl",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A shallow bronze basin with stylized flame carvings around the rim, greened with age patination."
  },
  {
    "name": "Ceremonial Obsidian Dagger",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A razor-sharp ritual knife flaked from jet-black volcanic glass, with a handle wrapped in gilded wire."
  },
  {
    "name": "Altar Cloth Embroidered with Silver Thread",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "35 gp",
    "valueGp": 35,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A heavy velvet runner dyed deep indigo and stitched with constellations in tarnished silver thread."
  },
  {
    "name": "Alabaster Statue Fragment of a Sun Deity",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "75 gp",
    "valueGp": 75,
    "weight": "12 lbs.",
    "weightLbs": 12,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "The finely sculpted bust and face of a radiant deity, broken at the shoulders from a larger monument."
  },
  {
    "name": "Gilded Incense Burner",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A brass censer coated in thin gold foil, pierced with lattice patterns depicting divine celestial rays."
  },
  {
    "name": "Holy Water Reliquary of Chased Silver",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "120 gp",
    "valueGp": 120,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A sealed cylinder of chased silver designed to hold consecrated water, topped with a crystal stopper."
  },
  {
    "name": "Chimes of Cast Bronze",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "20 gp",
    "valueGp": 20,
    "weight": "5 lbs.",
    "weightLbs": 5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A set of five tuned bronze wind chimes suspended from a carved mahogany frame."
  },
  {
    "name": "Stained Glass Rosette Panel Fragment",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "45 gp",
    "valueGp": 45,
    "weight": "6 lbs.",
    "weightLbs": 6,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "A lead-framed segment of antique stained glass depicting a haloed saintly figure."
  },
  {
    "name": "Brazen Sacrificial Basin",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "80 gp",
    "valueGp": 80,
    "weight": "25 lbs.",
    "weightLbs": 25,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A heavy cast brass tripod basin adorned with ram head handles, discolored by ancient ritual fires."
  },
  {
    "name": "Marble Statuette of a Veiled Priestess",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "200 gp",
    "valueGp": 200,
    "weight": "8 lbs.",
    "weightLbs": 8,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "An exquisitely detailed statuette carved from white marble with delicate drapery work."
  },
  {
    "name": "Gold-Leaf Votive Plaque",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "60 gp",
    "valueGp": 60,
    "weight": "1.5 lbs.",
    "weightLbs": 1.5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A bronze tablet covered in thin gold leaf, inscribed with a prayer of gratitude for a miraculous healing."
  },
  {
    "name": "Prayer Wheel of Engraved Brass",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "30 gp",
    "valueGp": 30,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A hand-held spinning brass cylinder containing a scroll of repeating sacred mantras."
  },
  {
    "name": "Jade-Inlaid Ceremonial Gong",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "350 gp",
    "valueGp": 350,
    "weight": "18 lbs.",
    "weightLbs": 18,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A resonant bronze gong rimmed with small cabochons of green jade, suspended from an oak stand."
  },
  {
    "name": "Carved Bone Shrine Icon",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A miniature pocket idol carved from a whale rib, representing a patron protector of travelers."
  },
  {
    "name": "Ornate Silver Candle Snuffer",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "12 gp",
    "valueGp": 12,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A long-handled silver snuffer ending in a hinged cone engraved with holy symbols."
  },
  {
    "name": "Serpent-Embossed Copper Candelabra",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "40 gp",
    "valueGp": 40,
    "weight": "7 lbs.",
    "weightLbs": 7,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A three-armed standing copper candelabra styled like entwined vipers holding candle sockets in their jaws."
  },
  {
    "name": "Velvet Ritual Robes with Gold Trim",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "5 lbs.",
    "weightLbs": 5,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "Ceremonial garments of deep crimson silk velvet with brocaded golden hems, worn by high priests."
  },
  {
    "name": "Stone Reliquary Box with Lapis Lazuli Inlays",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "180 gp",
    "valueGp": 180,
    "weight": "5 lbs.",
    "weightLbs": 5,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A small carved soapstone chest inlaid with deep blue lapis lazuli tiles, built to hold sacred relics."
  },
  {
    "name": "Carved Cedar Altar Screen Fragment",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A panel of aromatic cedar intricately pierced with floral patterns and holy verses."
  },
  {
    "name": "Crystal Flask for Anointing Oils",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "65 gp",
    "valueGp": 65,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A faceted rock crystal vessel with a silver screw-cap, still faint with the fragrance of myrrh."
  },
  {
    "name": "Chased Electrum Holy Symbol",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "90 gp",
    "valueGp": 90,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A medallion forged from electrum (a gold-silver alloy), detailed with high-relief divine iconography."
  },
  {
    "name": "Silver Ceremonial Bell",
    "category": "Temple Relic",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "1.5 lbs.",
    "weightLbs": 1.5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A pure silver handbell used during sanctification rites, producing a long clear ring."
  },
  {
    "name": "Terracotta Votive Vessel",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "8 gp",
    "valueGp": 8,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A painted earthenware urn used for burning aromatics during morning prayers."
  },
  {
    "name": "Bronze Altar Lantern with Mica Panes",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "35 gp",
    "valueGp": 35,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A hanging lantern with sheets of heat-resistant translucent mica instead of glass."
  },
  {
    "name": "Embossed Brass Libation Bowl",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "18 gp",
    "valueGp": 18,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A shallow pouring bowl with hammered motifs of grain sheaves and grapevines."
  },
  {
    "name": "Gilded Wood Shrine Canopy",
    "category": "Temple Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "110 gp",
    "valueGp": 110,
    "weight": "15 lbs.",
    "weightLbs": 15,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "An arching wooden archway coated in bright gold leaf, designed to frame an idol."
  },
  {
    "name": "Painted Ceramic Canopic Jar",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A glazed pottery jar topped with the carved head of a jackal, used to store preserved organs."
  },
  {
    "name": "Hammered Copper Funerary Mask",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A thin sheet of hammered copper shaped to fit over the face of a deceased noble, patinated green."
  },
  {
    "name": "Electrum Death Shroud Clip",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "35 gp",
    "valueGp": 35,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A heavy electrum brooch carved like a scarab beetle, used to fasten burial linens."
  },
  {
    "name": "Glazed Faience Shabti Figurine",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A turquoise-blue glazed ceramic figurine intended to serve the deceased in the afterlife."
  },
  {
    "name": "Gilded Wooden Sarcophagus Panel",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "150 gp",
    "valueGp": 150,
    "weight": "10 lbs.",
    "weightLbs": 10,
    "condition": "Fragile",
    "rarity": "Uncommon",
    "description": "A section of cedar sarcophagus painted with funerary glyphs and overlaid with leaf gold."
  },
  {
    "name": "Tarnished Bronze Urn with Engraved Runes",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "5 lbs.",
    "weightLbs": 5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A sealed funerary urn inscribed with wards against grave robbing and necromancy."
  },
  {
    "name": "Obsidian Eye Inlay from a Mummy Case",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "20 gp",
    "valueGp": 20,
    "weight": "0.2 lb.",
    "weightLbs": 0.2,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A pair of polished obsidian and white shell eyes pulled from a sarcophagus lid."
  },
  {
    "name": "Ceremonial Burial Dagger with Ivory Hilt",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "75 gp",
    "valueGp": 75,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "An unsharpened decorative blade buried alongside a warrior lord, featuring a carved elephant ivory hilt."
  },
  {
    "name": "Embroidered Linen Death Shroud",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "30 gp",
    "valueGp": 30,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "A long winding sheet of fine linen stitched with protective warding symbols in silver thread."
  },
  {
    "name": "Onyx Scarab Amulet",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "60 gp",
    "valueGp": 60,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A heavy black onyx beetle pendant placed over the heart of a mummified corpse."
  },
  {
    "name": "Mortuary Oil Lamp of Terracotta",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A clay lamp left at a tomb entrance, containing dried residue of scented ritual oil."
  },
  {
    "name": "Carved Bone Tomb Token",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A flattened disc of cattle bone stamped with the seal of a royal necropolis."
  },
  {
    "name": "Silver-Plated Death Mask",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "120 gp",
    "valueGp": 120,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Aged",
    "rarity": "Uncommon",
    "description": "A metallic portrait mask capturing the solemn visage of an ancient noble in silver finish."
  },
  {
    "name": "Lead Seals from an Ancient Tomb Door",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "Heavy stamped lead plugs that once sealed the entrance of a subterranean tomb chamber."
  },
  {
    "name": "Bronze Mortuary Bell",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A small handbell rung during burial processions to ward off evil spirits."
  },
  {
    "name": "Gold-Foil Burial Wreath",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Fragile",
    "rarity": "Uncommon",
    "description": "A delicate crown of laurel leaves beaten from pure gold foil, worn by interred royalty."
  },
  {
    "name": "Inscribed Slate Grave Marker Fragment",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "8 lbs.",
    "weightLbs": 8,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A broken piece of black slate bearing an epitaph written in archaic Common."
  },
  {
    "name": "Alabaster Ointment Jar",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "40 gp",
    "valueGp": 40,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A translucent white alabaster jar with a carved stopper, used to hold embalming perfumes."
  },
  {
    "name": "Terracotta Funerary Servant Statue",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "6 lbs.",
    "weightLbs": 6,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A painted clay figure of an archer or bearer created to accompany a lord in death."
  },
  {
    "name": "Carved Soapstone Effigy",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A smooth green soapstone carving of a sleeping guardian beast."
  },
  {
    "name": "Filigree Silver Ring on a Skeleton's Hand",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "30 gp",
    "valueGp": 30,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A delicate silver band inset with tiny garnets, recovered from an ancient burial pit."
  },
  {
    "name": "Gilded Bone Comb",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "45 gp",
    "valueGp": 45,
    "weight": "0.3 lb.",
    "weightLbs": 0.3,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "A fine-toothed toilet comb carved from ivory-toned bone with gold foil trim."
  },
  {
    "name": "Crypt Key of Cast Iron",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A heavy, eight-inch iron key with a skull-shaped bow, fitting ancient tomb locks."
  },
  {
    "name": "Incised Steatite Seal Stone",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "20 gp",
    "valueGp": 20,
    "weight": "0.2 lb.",
    "weightLbs": 0.2,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A cylindrical stamp stone used to mark royal grave goods with personal heraldry."
  },
  {
    "name": "Cedar Burial Box with Copper Strapping",
    "category": "Tomb Goods",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "35 gp",
    "valueGp": 35,
    "weight": "7 lbs.",
    "weightLbs": 7,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A small chest for personal possessions, bound in verdigris-covered copper bands."
  },
  {
    "name": "Rusted Iron Longsword",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A notched martial blade heavily pitted by centuries of damp tomb air, its leather grip decayed."
  },
  {
    "name": "Pitted Chainmail Shirt",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "20 gp",
    "valueGp": 20,
    "weight": "25 lbs.",
    "weightLbs": 25,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A heavy shirt of interlocking iron rings stiffened with red rust, missing several links."
  },
  {
    "name": "Tarnished Bronze Shortsword",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "An ancient leaf-shaped bronze weapon covered in a thick patina of green verdigris."
  },
  {
    "name": "Weathered Oak Shield with Iron Boss",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "3 gp",
    "valueGp": 3,
    "weight": "6 lbs.",
    "weightLbs": 6,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A round wooden shield split across the face, held together by a rusted iron center dome."
  },
  {
    "name": "Cracked Steel Breastplate",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "20 lbs.",
    "weightLbs": 20,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A once-fine steel cuirass bearing a deep gash from a warhammer strike, still retaining decorative inlay."
  },
  {
    "name": "Corroded Greatsword",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "6 lbs.",
    "weightLbs": 6,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A massive two-handed blade fused into its iron-rimmed scabbard by thick rust."
  },
  {
    "name": "Dull Iron Dagger with Bone Hilt",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A simple sidearm with a yellowed bone handle and a pitted, edge-worn blade."
  },
  {
    "name": "Rusted Iron Morningstar",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A spiked metal head attached to a splintered wooden shaft, dulled by rust and impact."
  },
  {
    "name": "Broken Spearhead of Damascened Steel",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "4 gp",
    "valueGp": 4,
    "weight": "1.5 lbs.",
    "weightLbs": 1.5,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "The snapped blade of a partisan or spear showing folded steel patterns beneath surface corrosion."
  },
  {
    "name": "Bent Heavy Crossbow",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "12 gp",
    "valueGp": 12,
    "weight": "18 lbs.",
    "weightLbs": 18,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A siege crossbow with a rusted iron prod and rotted hemp bowstring, suitable for salvage."
  },
  {
    "name": "Pitted Iron Greataxe",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "7 lbs.",
    "weightLbs": 7,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A broad double-bitted axe head darkened by oxidation, mounted on a cracked ash handle."
  },
  {
    "name": "Tarnished Brass Helmet with Horsehair Crest",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A high-crested guard helm with cheek guards, stained dark with age and dust."
  },
  {
    "name": "Splintered Lance with Faded Banner",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A knightly jousting weapon broken at mid-shaft, bearing a moth-eaten heraldic pennant."
  },
  {
    "name": "Rusted Scale Mail Vestment",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "30 lbs.",
    "weightLbs": 30,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "Overlapping iron scales sewn onto rotting leather backing, flaking rust at the touch."
  },
  {
    "name": "Ancient Bronze Shield with Dragon Motif",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "45 gp",
    "valueGp": 45,
    "weight": "7 lbs.",
    "weightLbs": 7,
    "condition": "Aged",
    "rarity": "Uncommon",
    "description": "A heavy bronze hoplite shield embossed with a relief of a coiled wyrm."
  },
  {
    "name": "Corroded Halberd Head",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "4 gp",
    "valueGp": 4,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "The axe and spike assembly of a polearm severed from its wooden shaft."
  },
  {
    "name": "Worn Leather Armor with Brass Studs",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "8 lbs.",
    "weightLbs": 8,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "Stiffened boiled leather chestpiece missing several brass rivets and torn at the buckles."
  },
  {
    "name": "Broken Scimitar with Intact Silver Pommel",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A curved blade snapped in half, featuring a silver pommel cap carved like a falcon head."
  },
  {
    "name": "Chipped War Pick",
    "category": "Rusted Equipment",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "3 gp",
    "valueGp": 3,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A heavy piercing hammer designed to puncture plate armor, now blunted and rusty."
  },
  {
    "name": "Antique Guard's Fluted Mace",
    "category": "Worn Equipment",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "8 gp",
    "valueGp": 8,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A six-flanged steel club with decorative grooves along the shaft."
  },
  {
    "name": "Cut Azurite",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "An opaque, deep mottling blue stone prized by jewelers for minor ornamental work."
  },
  {
    "name": "Polished Banded Agate",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A translucent stone displaying concentric bands of brown, white, and red."
  },
  {
    "name": "Blue Quartz Cabochon",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A pale blue quartz crystal polished into a smooth rounded dome."
  },
  {
    "name": "Eye Agate",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "An agate stone featuring ring-like markings resembling a watchful eye."
  },
  {
    "name": "Polished Hematite",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.02 lb.",
    "weightLbs": 0.02,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A heavy, metallic dark-grey stone with a brilliant mirror-like luster."
  },
  {
    "name": "Lapis Lazuli Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A rich azure stone speckled with flecks of golden pyrite."
  },
  {
    "name": "Malachite Cabochon",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "An opaque stone with swirling bands of light and dark green."
  },
  {
    "name": "Moss Agate",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A translucent clear agate containing greenish moss-like mineral filaments."
  },
  {
    "name": "Polished Obsidian Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A glassy black volcanic gem cut into a teardrop shape."
  },
  {
    "name": "Rhodochrosite Stone",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A rose-pink stone patterned with white zigzag bands."
  },
  {
    "name": "Tiger Eye Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A golden-brown chatoyant gem that catches the light like a feline pupil."
  },
  {
    "name": "Turquoise Stone",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A light blue-green stone with fine black vein matrix."
  },
  {
    "name": "Faceted Bloodstone",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A dark green jasper spotted with blood-red flecks of iron oxide."
  },
  {
    "name": "Carnelian Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A translucent reddish-orange chalcedony stone polished to a high sheen."
  },
  {
    "name": "Chrysoprase Stone",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "An apple-green variety of chalcedony gemstone."
  },
  {
    "name": "Faceted Citrine",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A brilliant yellow quartz stone cut into a radiant brilliant pattern."
  },
  {
    "name": "Polished Jasper",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "An opaque red and brown quartz mineral stone."
  },
  {
    "name": "Milky Moonstone",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A pearly white stone with a soft blue interior schiller sheen."
  },
  {
    "name": "Polished Black Onyx",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "50 gp",
    "valueGp": 50,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A smooth jet-black chalcedony stone popular in funerary jewelry."
  },
  {
    "name": "Faceted Amethyst",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A deep purple transparent quartz gemstone cut with sharp facets."
  },
  {
    "name": "Golden Amber Nugget",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.02 lb.",
    "weightLbs": 0.02,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A warm honey-colored piece of fossilized tree resin containing a prehistoric insect."
  },
  {
    "name": "Chrysoberyl Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A transparent yellowish-green stone with high refractive brilliance."
  },
  {
    "name": "Polished Red Coral",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.02 lb.",
    "weightLbs": 0.02,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A branch of precious crimson sea coral smoothed for mounting."
  },
  {
    "name": "Cut Almandine Garnet",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A dark violet-red stone cut into an oval brilliant shape."
  },
  {
    "name": "Carved Green Jade Cabochon",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.02 lb.",
    "weightLbs": 0.02,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "An imperial green jade stone smoothed into a dome."
  },
  {
    "name": "Faceted Jet Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A compact black lignite coal gem cut into a shiny multifaceted jewel."
  },
  {
    "name": "Lustrous Silver Pearl",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A perfectly spherical natural ocean pearl with silver iridescent iridescence."
  },
  {
    "name": "Deep Red Spinel",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "100 gp",
    "valueGp": 100,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A fiery magenta-red crystalline gemstone."
  },
  {
    "name": "Faceted Alexandrite",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "500 gp",
    "valueGp": 500,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Rare",
    "description": "A rare gem that shifts color from emerald green in daylight to ruby red in candlelight."
  },
  {
    "name": "Aquamarine Gem",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "500 gp",
    "valueGp": 500,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Rare",
    "description": "A clear pale blue-green beryl crystal of flawless transparency."
  },
  {
    "name": "Lustrous Black Pearl",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "500 gp",
    "valueGp": 500,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Rare",
    "description": "A rare dark pearl harvested from deep ocean waters with peacock iridescence."
  },
  {
    "name": "Golden Topaz",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "500 gp",
    "valueGp": 500,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Rare",
    "description": "A brilliant amber-gold gemstone cut into an emerald shape."
  },
  {
    "name": "Flawless Emerald",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "1,000 gp",
    "valueGp": 1000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Very Rare",
    "description": "A vivid green beryl gem cut into a step-cut rectangular facet."
  },
  {
    "name": "Deep Blue Sapphire",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "1,000 gp",
    "valueGp": 1000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Very Rare",
    "description": "A royal blue corundum jewel of immense clarity."
  },
  {
    "name": "Fiery Black Opal",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "1,000 gp",
    "valueGp": 1000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Very Rare",
    "description": "A dark body opal displaying vivid flashes of neon green, blue, and red pinfire."
  },
  {
    "name": "Star Ruby",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "1,000 gp",
    "valueGp": 1000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Very Rare",
    "description": "A crimson corundum cabochon exhibiting a six-rayed star asterism when illuminated."
  },
  {
    "name": "Flawless Cut Diamond",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "5,000 gp",
    "valueGp": 5000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Legendary",
    "description": "A large, brilliant-cut clear diamond of exceptional purity, suitable for powerful spell components."
  },
  {
    "name": "Deep Crimson Ruby",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "5,000 gp",
    "valueGp": 5000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Legendary",
    "description": "A pigeon-blood red corundum gem of radiant luster and historical value."
  },
  {
    "name": "Fiery Orange Jacinth",
    "category": "Gemstone",
    "type": "area loot",
    "theme": "General",
    "value": "5,000 gp",
    "valueGp": 5000,
    "weight": "0.01 lb.",
    "weightLbs": 0.01,
    "condition": "Pristine",
    "rarity": "Legendary",
    "description": "A rare reddish-orange zircon crystal cut into a brilliant cushion shape."
  },
  {
    "name": "Silver Chalice with Etched Vine Work",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "1.5 lbs.",
    "weightLbs": 1.5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A drinking vessel wrought of solid sterling silver, decorated with ivy motifs."
  },
  {
    "name": "Carved Bone Statuette of a Griffin",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A detailed miniature figurine sculpted from polished ivory-like cattle bone."
  },
  {
    "name": "Small Gold Ring with Engraved Crest",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A signet ring of 14k gold bearing a merchant guild seal."
  },
  {
    "name": "Cloth-of-Gold Vestments",
    "category": "Art Object",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "Ceremonial garments woven with fine golden threads."
  },
  {
    "name": "Black Velvet Mask with Thread-of-Silver",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A masquerade eye-mask lined with silk and embroidered with silver whorls."
  },
  {
    "name": "Silver Ewer",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A decorative silver pitcher used for serving wine during noble banquets."
  },
  {
    "name": "Gold Ring set with Small Rubies",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A broad gold band featuring three channel-set crimson ruby stones."
  },
  {
    "name": "Carved Ivory Statuette of an Elf Maiden",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A masterwork carving in solid elephant ivory displaying flowing hair and robes."
  },
  {
    "name": "Large Gold Bracelet",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A heavy hinged cuff bracelet of solid yellow gold with braided wire detail."
  },
  {
    "name": "Silver Necklace with Gemstone Pendant",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "0.3 lb.",
    "weightLbs": 0.3,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A fine silver chain holding a drop-pendant cut from teardrop amethyst."
  },
  {
    "name": "Embossed Bronze Crown",
    "category": "Art Object",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Uncommon",
    "description": "A ceremonial circlet wrought of heavy bronze and leafed in pale gold."
  },
  {
    "name": "Silk Robe with Gold Embroidery",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "250 gp",
    "valueGp": 250,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A high-court silk garment decorated along the collar and sleeves with gold bullion thread."
  },
  {
    "name": "Silver Chalice set with Lapis Lazuli",
    "category": "Art Object",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "750 gp",
    "valueGp": 750,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Pristine",
    "rarity": "Rare",
    "description": "A goblet of polished sterling silver adorned with four cabochon lapis lazuli stones around the bowl."
  },
  {
    "name": "Silk Tapestry depicting an Ancient Battle",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "750 gp",
    "valueGp": 750,
    "weight": "15 lbs.",
    "weightLbs": 15,
    "condition": "Aged",
    "rarity": "Rare",
    "description": "A large wall hanging woven with silk, silver, and gold threads depicting a dragon slain by knights."
  },
  {
    "name": "Carved Jade Dragon Figurine",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "750 gp",
    "valueGp": 750,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Pristine",
    "rarity": "Rare",
    "description": "A translucent green jade carving of a coiled oriental serpent holding a pearl in its claws."
  },
  {
    "name": "Fine Gold Chain set with a Fire Opal",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "2,500 gp",
    "valueGp": 2500,
    "weight": "0.3 lb.",
    "weightLbs": 0.3,
    "condition": "Pristine",
    "rarity": "Very Rare",
    "description": "An exquisite necklace of woven gold mesh holding a blazing orange fire opal of flawless quality."
  },
  {
    "name": "Old Masterpiece Painting",
    "category": "Art Object",
    "type": "area loot",
    "theme": "General",
    "value": "2,500 gp",
    "valueGp": 2500,
    "weight": "10 lbs.",
    "weightLbs": 10,
    "condition": "Aged",
    "rarity": "Very Rare",
    "description": "An oil portrait on wood panel by a renowned Renaissance artist in a heavy gilt frame."
  },
  {
    "name": "Jeweled Gold Crown",
    "category": "Art Object",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "7,500 gp",
    "valueGp": 7500,
    "weight": "4 lbs.",
    "weightLbs": 4,
    "condition": "Pristine",
    "rarity": "Legendary",
    "description": "A majestic royal tiara of pure gold studded with rubies, sapphires, and large brilliant diamonds."
  },
  {
    "name": "Pegasus Feather Frozen in Amber",
    "category": "Trinket",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "0.2 lb.",
    "weightLbs": 0.2,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A translucent amber pebble containing a single iridescent white feather."
  },
  {
    "name": "Brass Pocket Compass (Points to Temple)",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A handheld mariner's compass whose needle always aligns toward the nearest sacred altar."
  },
  {
    "name": "Glass Vial of Iridescent Sand",
    "category": "Trinket",
    "type": "area loot",
    "theme": "General",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "0.3 lb.",
    "weightLbs": 0.3,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A sealed glass tube containing shimmering sand harvested from a fey crossing."
  },
  {
    "name": "Old Copper Coin from a Lost Realm",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A heavy square copper coin stamped with the profile of an ancient tyrant king."
  },
  {
    "name": "Clapperless Silver Bell",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A small desk bell with no internal striker that still emits a soft clear tone when shaken."
  },
  {
    "name": "Wooden Puzzle Box smelling of Cedar",
    "category": "Trinket",
    "type": "area loot",
    "theme": "General",
    "value": "8 gp",
    "valueGp": 8,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "An interlocking wooden trick box requiring 12 distinct steps to open."
  },
  {
    "name": "Dried Toad in a Glass Orb",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "3 gp",
    "valueGp": 3,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A mummified amphibian suspended inside a solid blown glass marble."
  },
  {
    "name": "Mechanical Brass Beetle",
    "category": "Trinket",
    "type": "area loot",
    "theme": "General",
    "value": "30 gp",
    "valueGp": 30,
    "weight": "0.5 lb.",
    "weightLbs": 0.5,
    "condition": "Aged",
    "rarity": "Uncommon",
    "description": "A wind-up clockwork insect whose metal legs click and flutter for 30 seconds when turned."
  },
  {
    "name": "Pouch of Etched Runestones",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "4 gp",
    "valueGp": 4,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A drawstring leather bag containing 5 river pebbles engraved with dwarven runes."
  },
  {
    "name": "Mummified Goblin Hand",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "0.2 lb.",
    "weightLbs": 0.2,
    "condition": "Fragile",
    "rarity": "Common",
    "description": "A shriveled desiccated hand tied with leather thongs, worn as a macabre luck charm."
  },
  {
    "name": "Bone Skeleton Key",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A key filed from a human femur bone, fits no known lock."
  },
  {
    "name": "Tarnished Copper Locket with Pressed Flower",
    "category": "Trinket",
    "type": "area loot",
    "theme": "Tomb / Crypt",
    "value": "3 gp",
    "valueGp": 3,
    "weight": "0.1 lb.",
    "weightLbs": 0.1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "An oval hinged locket containing a petrified black rose petal."
  },
  {
    "name": "Iron Wall Sconce with Melted Tallow Wax",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "5 sp",
    "valueGp": 0.5,
    "weight": "3 lbs.",
    "weightLbs": 3,
    "condition": "Rusted",
    "rarity": "Common",
    "description": "A torch bracket forged from iron, covered in thick layers of yellowed candle wax."
  },
  {
    "name": "Tarnished Copper Lantern",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A hooded oil lamp with brass fittings and scratched glass panes."
  },
  {
    "name": "Heavy Oak Chest with Iron Bands",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "25 lbs.",
    "weightLbs": 25,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A sturdy storage trunk reinforced with riveted iron straps, key missing."
  },
  {
    "name": "Rotted Velvet Drapery with Tassels",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "8 lbs.",
    "weightLbs": 8,
    "condition": "Damaged",
    "rarity": "Common",
    "description": "A heavy curtain salvaged from a noble's chamber, discolored by dampness."
  },
  {
    "name": "Cast Iron Cauldron",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "15 lbs.",
    "weightLbs": 15,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A three-legged cooking pot coated in soot, useful for alchemy or cooking."
  },
  {
    "name": "Intact Ceramic Wine Amphora",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "10 lbs.",
    "weightLbs": 10,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A tall terracotta jug with twin handles, sealed with pitch."
  },
  {
    "name": "Brass Hourglass",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "1.5 lbs.",
    "weightLbs": 1.5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A 1-hour sand timer housed in a turned brass framework."
  },
  {
    "name": "Bundle of Pitch Torches (Set of 6)",
    "category": "Scavenge",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "6 cp",
    "valueGp": 0.06,
    "weight": "6 lbs.",
    "weightLbs": 6,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "Wooden stakes wrapped in resin-soaked cloth, ready for lighting."
  },
  {
    "name": "Coarse Hemp Rope (50 feet)",
    "category": "Scavenge",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "10 lbs.",
    "weightLbs": 10,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "Strong three-strand braided hemp cordage."
  },
  {
    "name": "Iron Pitons & Hammer Set",
    "category": "Scavenge",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "2 gp",
    "valueGp": 2,
    "weight": "5 lbs.",
    "weightLbs": 5,
    "condition": "Aged",
    "rarity": "Common",
    "description": "Ten notched iron spikes and a heavy piton hammer in a canvas pouch."
  },
  {
    "name": "Carved Pewter Goblet",
    "category": "Dungeon Decor",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "8 sp",
    "valueGp": 0.8,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A heavy pewter drinking cup engraved with hunting hounds."
  },
  {
    "name": "Leather Map Case with Brass Endcaps",
    "category": "Scavenge",
    "type": "area loot",
    "theme": "Dungeon / Cave",
    "value": "1 gp",
    "valueGp": 1,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Aged",
    "rarity": "Common",
    "description": "A water-resistant cylinder designed to keep scrolls dry."
  },
  {
    "name": "Electrum Bullion Bar",
    "category": "Trade Goods",
    "type": "area loot",
    "theme": "General",
    "value": "25 gp",
    "valueGp": 25,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A stamped ingot of gold-silver alloy marked with mint hallmarks."
  },
  {
    "name": "Chased Silver Ingot",
    "category": "Trade Goods",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "2 lbs.",
    "weightLbs": 2,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A commercial bar of refined silver trade metal."
  },
  {
    "name": "Bolt of Fine Silk Cloth",
    "category": "Trade Goods",
    "type": "area loot",
    "theme": "General",
    "value": "10 gp",
    "valueGp": 10,
    "weight": "5 lbs.",
    "weightLbs": 5,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A 10-yard roll of woven emerald-green mulberry silk fabric."
  },
  {
    "name": "Sack of Saffron Spices",
    "category": "Trade Goods",
    "type": "area loot",
    "theme": "General",
    "value": "15 gp",
    "valueGp": 15,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "A sealed linen bag containing dried threads of rare crocus spice."
  },
  {
    "name": "Cake of Fragrant Frankincense",
    "category": "Trade Goods",
    "type": "area loot",
    "theme": "Ancient Temple",
    "value": "5 gp",
    "valueGp": 5,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Common",
    "description": "A block of hardened aromatic resin used for sacred incense."
  },
  {
    "name": "Jar of Ultramarine Lapis Pigment",
    "category": "Trade Goods",
    "type": "area loot",
    "theme": "General",
    "value": "20 gp",
    "valueGp": 20,
    "weight": "1 lb.",
    "weightLbs": 1,
    "condition": "Pristine",
    "rarity": "Uncommon",
    "description": "Finely ground crushed lapis lazuli powder used by master painters and scribes."
  }
];

export const GENERAL_LOOT_ROLL_TABLE: RollTableEntity = {
  id: 'srd-table-general-dungeon-loot',
  type: 'rollTable',
  name: 'Dungeon, Relic & General Loot',
  category: 'Loot',
  theme: 'All',
  diceFormula: '1d162',
  description: 'Comprehensive general loot, dungeon decor, gemstones, art objects, and antiquities.',
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
  columns: [
    { key: 'category', label: 'Category', type: 'badge' },
    { key: 'type', label: 'Type', type: 'badge' },
    { key: 'theme', label: 'Theme', type: 'badge' },
    { key: 'value', label: 'Value', type: 'badge' },
    { key: 'weight', label: 'Weight', type: 'text' },
    { key: 'condition', label: 'Condition', type: 'badge' },
    { key: 'rarity', label: 'Rarity', type: 'badge' },
    { key: 'description', label: 'Description', type: 'text' }
  ],
  items: GENERAL_LOOT_ITEMS.map((item, idx) => ({
    id: `loot-row-${idx + 1}`,
    rangeMin: idx + 1,
    rangeMax: idx + 1,
    result: item.name,
    values: {
      category: item.category,
      type: item.type,
      theme: item.theme,
      value: item.value,
      weight: item.weight,
      condition: item.condition,
      rarity: item.rarity,
      description: item.description
    }
  }))
};

