import { MonsterEntity } from '../../types/monster';

export const SRD_MONSTERS: MonsterEntity[] = [
  {
    id: 'srd-goblin',
    type: 'monster',
    name: 'Goblin',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Small',
    monsterType: 'Humanoid (goblinoid)',
    alignment: 'neutral evil',
    armorClass: 15,
    armorDesc: 'leather armor, shield',
    hitPoints: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    skills: 'Stealth +6',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'Common, Goblin',
    challengeRating: '1/4',
    experiencePoints: 50,
    environment: 'Forest, Grassland, Underground',
    traits: [
      {
        name: 'Nimble Escape',
        desc: 'The goblin can take the Disengage or Hide action as a bonus action on each of its turns.',
      },
    ],
    actions: [
      {
        name: 'Scimitar',
        desc: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.',
        attackBonus: 4,
        damageDice: '1d6+2',
        damageType: 'slashing',
      },
      {
        name: 'Shortbow',
        desc: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackBonus: 4,
        damageDice: '1d6+2',
        damageType: 'piercing',
      },
    ],
  },
  {
    id: 'srd-bugbear',
    type: 'monster',
    name: 'Bugbear',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Medium',
    monsterType: 'Humanoid (goblinoid)',
    alignment: 'chaotic evil',
    armorClass: 16,
    armorDesc: 'hide armor, shield',
    hitPoints: 27,
    hitDice: '5d8 + 5',
    speed: '30 ft.',
    abilities: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    skills: 'Stealth +6, Survival +2',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common, Goblin',
    challengeRating: '1',
    experiencePoints: 200,
    environment: 'Forest, Underground',
    traits: [
      {
        name: 'Brute',
        desc: 'A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).',
      },
      {
        name: 'Surprise Attack',
        desc: 'If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack.',
      },
    ],
    actions: [
      {
        name: 'Morningstar',
        desc: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage.',
        attackBonus: 4,
        damageDice: '2d8+2',
        damageType: 'piercing',
      },
      {
        name: 'Javelin',
        desc: 'Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 9 (2d6 + 2) piercing damage in melee or 5 (1d6 + 2) piercing damage at range.',
        attackBonus: 4,
        damageDice: '2d6+2',
        damageType: 'piercing',
      },
    ],
  },
  {
    id: 'srd-skeleton',
    type: 'monster',
    name: 'Skeleton',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Medium',
    monsterType: 'Undead',
    alignment: 'lawful evil',
    armorClass: 13,
    armorDesc: 'armor scraps',
    hitPoints: 13,
    hitDice: '2d8 + 4',
    speed: '30 ft.',
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    vulnerabilities: 'bludgeoning',
    immunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'understands languages it knew in life but cannot speak',
    challengeRating: '1/4',
    experiencePoints: 50,
    actions: [
      {
        name: 'Shortsword',
        desc: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackBonus: 4,
        damageDice: '1d6+2',
        damageType: 'piercing',
      },
      {
        name: 'Shortbow',
        desc: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackBonus: 4,
        damageDice: '1d6+2',
        damageType: 'piercing',
      },
    ],
  },
  {
    id: 'srd-bandit-captain',
    type: 'monster',
    name: 'Bandit Captain',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Medium',
    monsterType: 'Humanoid (any race)',
    alignment: 'any non-lawful alignment',
    armorClass: 15,
    armorDesc: 'studded leather',
    hitPoints: 65,
    hitDice: '10d8 + 20',
    speed: '30 ft.',
    abilities: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    savingThrows: 'Str +4, Dex +5, Wis +2',
    skills: 'Athletics +4, Deception +4',
    senses: 'passive Perception 10',
    languages: 'any two languages',
    challengeRating: '2',
    experiencePoints: 450,
    actions: [
      {
        name: 'Multiattack',
        desc: 'The captain makes three melee attacks: two with its scimitar and one with its dagger. Or the captain makes two ranged attacks with its daggers.',
      },
      {
        name: 'Scimitar',
        desc: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.',
        attackBonus: 5,
        damageDice: '1d6+3',
        damageType: 'slashing',
      },
      {
        name: 'Dagger',
        desc: 'Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 5 (1d4 + 3) piercing damage.',
        attackBonus: 5,
        damageDice: '1d4+3',
        damageType: 'piercing',
      },
    ],
    reactions: [
      {
        name: 'Parry',
        desc: 'The captain adds 2 to its AC against one melee attack that would hit it. To do so, the captain must see the attacker and be wielding a melee weapon.',
      },
    ],
  },
  {
    id: 'srd-ogre',
    type: 'monster',
    name: 'Ogre',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Large',
    monsterType: 'Giant',
    alignment: 'chaotic evil',
    armorClass: 11,
    armorDesc: 'hide armor',
    hitPoints: 59,
    hitDice: '7d10 + 21',
    speed: '40 ft.',
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'Common, Giant',
    challengeRating: '2',
    experiencePoints: 450,
    actions: [
      {
        name: 'Greatclub',
        desc: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage.',
        attackBonus: 6,
        damageDice: '2d8+4',
        damageType: 'bludgeoning',
      },
      {
        name: 'Javelin',
        desc: 'Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 11 (2d6 + 4) piercing damage.',
        attackBonus: 6,
        damageDice: '2d6+4',
        damageType: 'piercing',
      },
    ],
  },
  {
    id: 'srd-owlbear',
    type: 'monster',
    name: 'Owlbear',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Large',
    monsterType: 'Monstrosity',
    alignment: 'unaligned',
    armorClass: 13,
    armorDesc: 'natural armor',
    hitPoints: 59,
    hitDice: '7d10 + 21',
    speed: '40 ft.',
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    skills: 'Perception +3',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: '—',
    challengeRating: '3',
    experiencePoints: 700,
    traits: [
      {
        name: 'Keen Sight and Smell',
        desc: 'The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell.',
      },
    ],
    actions: [
      {
        name: 'Multiattack',
        desc: 'The owlbear makes two attacks: one with its beak and one with its claws.',
      },
      {
        name: 'Beak',
        desc: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one creature. Hit: 10 (1d10 + 5) piercing damage.',
        attackBonus: 7,
        damageDice: '1d10+5',
        damageType: 'piercing',
      },
      {
        name: 'Claws',
        desc: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) slashing damage.',
        attackBonus: 7,
        damageDice: '2d8+5',
        damageType: 'slashing',
      },
    ],
  },
  {
    id: 'srd-young-red-dragon',
    type: 'monster',
    name: 'Young Red Dragon',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Large',
    monsterType: 'Dragon',
    alignment: 'chaotic evil',
    armorClass: 18,
    armorDesc: 'natural armor',
    hitPoints: 178,
    hitDice: '17d10 + 85',
    speed: '40 ft., climb 40 ft., fly 80 ft.',
    abilities: { str: 23, dex: 10, con: 21, int: 14, wis: 11, cha: 19 },
    savingThrows: 'Dex +4, Con +9, Wis +4, Cha +8',
    skills: 'Perception +8, Stealth +4',
    immunities: 'fire',
    senses: 'blindsight 30 ft., darkvision 120 ft., passive Perception 18',
    languages: 'Common, Draconic',
    challengeRating: '10',
    experiencePoints: 5900,
    actions: [
      {
        name: 'Multiattack',
        desc: 'The dragon makes three attacks: one with its bite and two with its claws.',
      },
      {
        name: 'Bite',
        desc: 'Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 17 (2d10 + 6) piercing damage plus 3 (1d6) fire damage.',
        attackBonus: 10,
        damageDice: '2d10+6',
        damageType: 'piercing',
      },
      {
        name: 'Claw',
        desc: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 13 (2d6 + 6) slashing damage.',
        attackBonus: 10,
        damageDice: '2d6+6',
        damageType: 'slashing',
      },
      {
        name: 'Fire Breath (Recharge 5–6)',
        desc: 'The dragon exhales fire in a 30-foot cone. Each creature in that area must make a DC 17 Dexterity saving throw, taking 56 (16d6) fire damage on a failed save, or half as much damage on a successful one.',
        damageDice: '16d6',
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'srd-beholder',
    type: 'monster',
    name: 'Beholder',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    size: 'Large',
    monsterType: 'Aberration',
    alignment: 'lawful evil',
    armorClass: 18,
    armorDesc: 'natural armor',
    hitPoints: 180,
    hitDice: '19d10 + 76',
    speed: '0 ft., fly 20 ft. (hover)',
    abilities: { str: 10, dex: 14, con: 18, int: 17, wis: 15, cha: 17 },
    savingThrows: 'Int +8, Wis +7, Cha +8',
    skills: 'Perception +12',
    conditionImmunities: 'prone',
    senses: 'darkvision 120 ft., passive Perception 22',
    languages: 'Deep Speech, Undercommon',
    challengeRating: '13',
    experiencePoints: 10000,
    traits: [
      {
        name: 'Antimagic Cone',
        desc: 'The beholder’s central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the beholder decides which way the cone faces and whether the cone is active.',
      },
    ],
    actions: [
      {
        name: 'Bite',
        desc: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 14 (4d6) piercing damage.',
        attackBonus: 5,
        damageDice: '4d6',
        damageType: 'piercing',
      },
      {
        name: 'Eye Rays',
        desc: 'The beholder shoots three of the following magical eye rays at random (reroll duplicates), choosing one to three targets it can see within 120 ft.: 1. Charm Ray | 2. Paralyzing Ray | 3. Fear Ray | 4. Slowing Ray | 5. Enervation Ray | 6. Telekinetic Ray | 7. Sleep Ray | 8. Petrification Ray | 9. Disintegration Ray | 10. Death Ray.',
      },
    ],
    legendaryActions: [
      {
        name: 'Eye Ray',
        desc: 'The beholder uses one random eye ray.',
      },
    ],
  },
];
