import { SpellEntity } from '../../types/spell';

export const SRD_SPELLS: SpellEntity[] = [
  // --- EVOCATION ---
  {
    id: 'srd-fireball',
    type: 'spell',
    name: 'Fireball',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Evocation',
    element: 'fire',
    shape: 'sphere',
    range: '150 feet',
    rangeFeet: 150,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A tiny ball of bat guano and sulfur' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    aoe: { shape: 'sphere', sizeFeet: 20 },
  },
  {
    id: 'srd-cone-of-cold',
    type: 'spell',
    name: 'Cone of Cold',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 5,
    school: 'Evocation',
    element: 'cold',
    shape: 'cone',
    range: 'Self (60-foot cone)',
    rangeFeet: 60,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A small crystal or glass cone' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
    aoe: { shape: 'cone', sizeFeet: 60 },
  },
  {
    id: 'srd-burning-hands',
    type: 'spell',
    name: 'Burning Hands',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Evocation',
    element: 'fire',
    shape: 'cone',
    range: 'Self (15-foot cone)',
    rangeFeet: 15,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
    aoe: { shape: 'cone', sizeFeet: 15 },
  },
  {
    id: 'srd-lightning-bolt',
    type: 'spell',
    name: 'Lightning Bolt',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Evocation',
    element: 'lightning',
    shape: 'line',
    range: 'Self (100-foot line)',
    rangeFeet: 100,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A bit of fur and a rod of amber, crystal, or glass' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    aoe: { shape: 'line', sizeFeet: 100, lengthFeet: 100, widthFeet: 5 },
  },
  {
    id: 'srd-thunderwave',
    type: 'spell',
    name: 'Thunderwave',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Evocation',
    element: 'thunder',
    shape: 'cube',
    range: 'Self (15-foot cube)',
    rangeFeet: 15,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    aoe: { shape: 'cube', sizeFeet: 15 },
  },
  {
    id: 'srd-shatter',
    type: 'spell',
    name: 'Shatter',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 2,
    school: 'Evocation',
    element: 'thunder',
    shape: 'sphere',
    range: '60 feet',
    rangeFeet: 60,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A chip of mica' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    description: 'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one.',
    aoe: { shape: 'sphere', sizeFeet: 10 },
  },
  {
    id: 'srd-cure-wounds',
    type: 'spell',
    name: 'Cure Wounds',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Evocation',
    element: 'radiant',
    shape: 'none',
    range: 'Touch',
    rangeFeet: 5,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger'],
    description: 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
  },

  // --- CONJURATION ---
  {
    id: 'srd-spirit-guardians',
    type: 'spell',
    name: 'Spirit Guardians',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Conjuration',
    element: 'radiant',
    shape: 'sphere',
    range: 'Self (15-foot sphere)',
    rangeFeet: 15,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A holy symbol' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    classes: ['Cleric'],
    description: 'You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. When a creature enters the area for the first time on a turn or starts its turn there, you can cause the spirits to take radiant (or necrotic) damage equal to 3d8 on a failed Wisdom saving throw.',
    aoe: { shape: 'sphere', sizeFeet: 15 },
  },
  {
    id: 'srd-web',
    type: 'spell',
    name: 'Web',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 2,
    school: 'Conjuration',
    element: 'none',
    shape: 'cube',
    range: '60 feet',
    rangeFeet: 60,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A bit of spiderweb' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area. Creatures entering must make a Dexterity save or become Restrained.',
    aoe: { shape: 'cube', sizeFeet: 20 },
  },
  {
    id: 'srd-fog-cloud',
    type: 'spell',
    name: 'Fog Cloud',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Conjuration',
    element: 'cold',
    shape: 'sphere',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard'],
    description: 'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.',
    aoe: { shape: 'sphere', sizeFeet: 20 },
  },
  {
    id: 'srd-cloudkill',
    type: 'spell',
    name: 'Cloudkill',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 5,
    school: 'Conjuration',
    element: 'poison',
    shape: 'sphere',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners. It is heavily obscured. Each creature in the area takes 5d8 poison damage on a failed Constitution save.',
    aoe: { shape: 'sphere', sizeFeet: 20 },
  },

  // --- ENCHANTMENT ---
  {
    id: 'srd-hypnotic-pattern',
    type: 'spell',
    name: 'Hypnotic Pattern',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Enchantment',
    element: 'psychic',
    shape: 'cube',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: false, somatic: true, material: true, materialCost: 'A glowing stick of incense or a crystal vial of phosphorescent material' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    description: 'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration and is incapacitated.',
    aoe: { shape: 'cube', sizeFeet: 30 },
  },
  {
    id: 'srd-bless',
    type: 'spell',
    name: 'Bless',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Enchantment',
    element: 'radiant',
    shape: 'sphere',
    range: '30 feet',
    rangeFeet: 30,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A sprinkling of holy water' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    classes: ['Cleric', 'Paladin'],
    description: 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.',
  },
  {
    id: 'srd-sleep',
    type: 'spell',
    name: 'Sleep',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Enchantment',
    element: 'psychic',
    shape: 'sphere',
    range: '90 feet',
    rangeFeet: 90,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A pinch of fine sand, rose petals, or a cricket' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    description: 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within a 20-foot-radius sphere are affected in ascending order of their current hit points.',
    aoe: { shape: 'sphere', sizeFeet: 20 },
  },

  // --- NECROMANCY ---
  {
    id: 'srd-circle-of-death',
    type: 'spell',
    name: 'Circle of Death',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 6,
    school: 'Necromancy',
    element: 'necrotic',
    shape: 'sphere',
    range: '150 feet',
    rangeFeet: 150,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'The powder of a crushed black pearl worth at least 500 gp' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    description: 'A sphere of negative energy ripples out in a 60-foot-radius sphere from a point within range. Each creature in that area must make a Constitution saving throw. A target takes 8d6 necrotic damage on a failed save, or half as much damage on a successful one.',
    aoe: { shape: 'sphere', sizeFeet: 60 },
  },
  {
    id: 'srd-arms-of-hadar',
    type: 'spell',
    name: 'Arms of Hadar',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Necromancy',
    element: 'necrotic',
    shape: 'sphere',
    range: 'Self (10-foot sphere)',
    rangeFeet: 10,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Warlock'],
    description: 'You invoke the power of Hadar, the Dark Hunger. Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you. Each creature in that area must make a Strength saving throw. On a failed save, a target takes 2d6 necrotic damage and cannot take reactions.',
    aoe: { shape: 'sphere', sizeFeet: 10 },
  },

  // --- ABJURATION ---
  {
    id: 'srd-shield',
    type: 'spell',
    name: 'Shield',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Abjuration',
    element: 'force',
    shape: 'none',
    range: 'Self',
    rangeFeet: 0,
    castingTime: '1 reaction',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 round',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
  },
  {
    id: 'srd-dispel-magic',
    type: 'spell',
    name: 'Dispel Magic',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Abjuration',
    element: 'none',
    shape: 'sphere',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard'],
    description: 'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability (DC 10 + the spell\'s level).',
    aoe: { shape: 'sphere', sizeFeet: 10 },
  },

  // --- ILLUSION ---
  {
    id: 'srd-silence',
    type: 'spell',
    name: 'Silence',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 2,
    school: 'Illusion',
    element: 'thunder',
    shape: 'sphere',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    classes: ['Bard', 'Cleric', 'Ranger'],
    description: 'For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened.',
    aoe: { shape: 'sphere', sizeFeet: 20 },
  },
  {
    id: 'srd-color-spray',
    type: 'spell',
    name: 'Color Spray',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Illusion',
    element: 'radiant',
    shape: 'cone',
    range: 'Self (15-foot cone)',
    rangeFeet: 15,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A pinch of powder or sand colored red, yellow, and blue' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'A dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone are affected in ascending order of their current hit points, becoming blinded.',
    aoe: { shape: 'cone', sizeFeet: 15 },
  },

  // --- TRANSMUTATION ---
  {
    id: 'srd-slow',
    type: 'spell',
    name: 'Slow',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Transmutation',
    element: 'none',
    shape: 'cube',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A drop of molasses' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration, having its speed halved and taking a -2 penalty to AC and Dex saves.',
    aoe: { shape: 'cube', sizeFeet: 40 },
  },
  {
    id: 'srd-haste',
    type: 'spell',
    name: 'Haste',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 3,
    school: 'Transmutation',
    element: 'none',
    shape: 'none',
    range: '30 feet',
    rangeFeet: 30,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'A shaving of licorice root' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    description: 'Choose a willing creature that you can see within range. Until the spell ends, the target’s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.',
  },

  // --- DIVINATION ---
  {
    id: 'srd-detect-magic',
    type: 'spell',
    name: 'Detect Magic',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 1,
    school: 'Divination',
    element: 'radiant',
    shape: 'sphere',
    range: 'Self (30-foot sphere)',
    rangeFeet: 30,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard'],
    description: 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic.',
    aoe: { shape: 'sphere', sizeFeet: 30 },
  },
  {
    id: 'srd-moonbeam',
    type: 'spell',
    name: 'Moonbeam',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    level: 2,
    school: 'Evocation',
    element: 'radiant',
    shape: 'cylinder',
    range: '120 feet',
    rangeFeet: 120,
    castingTime: '1 action',
    components: { verbal: true, somatic: true, material: true, materialCost: 'Several seeds of any moonseed plant and a piece of opalescent feldspar' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    classes: ['Druid'],
    description: 'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. When a creature enters the spell\'s area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames dealing 2d10 radiant damage on a failed Con save.',
    aoe: { shape: 'cylinder', sizeFeet: 5 },
  },
];
